# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "pages", :force => true do |t|
    t.column "title",         :string
    t.column "permanentlink", :string
    t.column "body",          :text
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "photos", :force => true do |t|
    t.column "user_id",      :integer
    t.column "title",        :string
    t.column "body",         :text
    t.column "created_at",   :datetime
    t.column "content_type", :string,   :limit => 100
    t.column "filename",     :string
    t.column "path",         :string
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "geo_lat",      :float
    t.column "geo_long",     :float
    t.column "show_geo",     :boolean,                 :default => true, :null => false
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer, :null => false
    t.column "user_id", :integer, :null => false
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id", "taggable_id", "taggable_type"], :name => "index_taggings_on_tag_id_and_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  add_index "tags", ["name"], :name => "index_tags_on_name"

  create_table "users", :force => true do |t|
    t.column "username",        :string,   :limit => 64,  :default => "",   :null => false
    t.column "email",           :string,   :limit => 128, :default => "",   :null => false
    t.column "hashed_password", :string,   :limit => 64
    t.column "enabled",         :boolean,                 :default => true, :null => false
    t.column "profile",         :text
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "last_login_at",   :datetime
    t.column "photos_count",    :integer
  end

  add_index "users", ["username"], :name => "index_users_on_username"

end
